# Regression test for H323Transport::CleanUpOnTermination().

PROG := transport_cleanup_test
SOURCES := main.cxx

ifndef OPENH323DIR
OPENH323DIR := $(CURDIR)/../..
endif

include $(OPENH323DIR)/openh323u.mak
